name: Build & Test (PR to dev)

on:
  pull_request:
    branches:
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout compose-stack repository
        uses: actions/checkout@v3
        with:
          repository: one-more-task-manager/compose-stack
          path: compose-stack

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t img .

      - name: Build and start dependencies using Docker Compose
        run: docker compose -f compose-stack/docker-compose-dev.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 30  # Wait for 30 seconds (adjust depending on your setup) to make sure the containers are ready

      - name: Run integration tests inside img container
        run: docker run --network compose-stack_default img mvn -B verify

      - name: Tear down Docker containers
        run: docker compose -f compose-stack/docker-compose-dev.yml down
