# .github/workflows/pr-dev-build-test.yml
name: Build & Test (PR to dev)

on:
  pull_request:
    branches:
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout compose-stack repository
        uses: actions/checkout@v3
        with:
          owner: one-more-task-manager
          repo: compose-stack

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers using Docker Compose
        run: docker compose -f compose-stack/docker-compose-local.yml up -d --build

      - name: Wait for services to be ready
        run: |
          docker compose -f compose-stack/docker-compose-local.yml ps
          docker compose -f compose-stack/docker-compose-local.yml wait

      - name: Run integration tests
        run: docker exec rest-api mvn -B verify

      - name: Tear down Docker containers
        run: docker compose -f compose-stack/docker-compose-local.yml down
